name: ci_cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm ci

    - name: Start Docker containers
      run: docker compose up -d
      env:
        POSTGRES_CONTAINER: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        POSTGRES_PORT: 5436
        REDIS_PASSWORD: redis
        
    - name: Run Prisma migrations
      run: |
        npx prisma migrate deploy
        npx prisma generate
      env : 
        DATABASE_URL : postgresql://postgres:postgres@localhost:5436/postgres
        
    - name: Run lint
      run: npm run lint

    - name: Run linttypes
      run: npm run lint:types

    - name: Run build
      run: npm run build
      env: 
        REDIS_PASSWORD: redis
      
    - name: Shutdown Docker
      run: docker compose down

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: github.actor == 'Ddkotl' 
    steps:
      - name: Show runner IP
        run: curl ifconfig.me
    
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Start Docker containers
        run: docker compose up -d
        env:
          POSTGRES_CONTAINER: ${{secrets.POSTGRES_CONTAINER}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
        
      - name: Run Prisma migrations
        run: |
          npx prisma migrate deploy
          npx prisma generate
        env : 
          DATABASE_URL : ${{secrets.DATABASE_URL}}

      - name: Run lint
        run: npm run lint

      - name: Run linttypes
        run: npm run lint:types
        
      - name: Run build
        run: npm run build
        env: 
          REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          WORKER_SECRET: ${{secrets.WORKER_SECRET}}
          ACTIV_SECRET: ${{secrets.ACTIV_SECRET}}
          APP_DOMEN: ${{secrets.APP_DOMEN}}
          BACKUP_DIR: ${{secrets.BACKUP_DIR}}
          POSTGRES_CONTAINER: ${{secrets.POSTGRES_CONTAINER}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Deploy to server
        run: |
          rsync -az --delete .next dist node_modules ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/admin/www/tg-clicker/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} bash -lc "
            cd /home/admin/www/tg-clicker &&
            git reset --hard origin/main &&
            cd scripts &&
            chmod +x deploy.sh &&
           ./deploy.sh
           "
